### ISSUE TITLE
关于使用DataParallel训练

### ISSUE THREAD

**Issue by buptxyb666** [ZiyiZhang27/HRNeXt#3]
你好，关注到HRNext在没有预训练情况下取得如此优异的性能。我发现将HRNext模型用到CenterNet codebase中无法通过multi-gpu训练（DataParallel()），单卡训练是正常的，使用2卡训练变得很慢，大概5s / iteration，八卡启动后就没有反应了。我猜测是多卡通信的问题。其他模型如HRNet多卡都是正常训练的，请问网络有啥操作造成的这个问题。

**Comment by buptxyb666** [comment]
同步BN也换成了BN

**Comment by ZiyiZhang27** [comment]
你好！不知你是直接将本文代码迁移过去还是自己重写的呢，你是否有开启本文代码中的with_cp开关呢？我猜测在多卡训练中开启梯度checkpoint功能可能会导致该问题，虽然本论文的实验也都使用了该功能并且没有问题，但是可能是出于mmpose自身的框架优化才避免了此类bug的产生，具体的产生原因我也不是很了解

**Comment by buptxyb666** [comment]
我直接把model迁移过去了，把with_cp关掉了目前可以训了，但是在八卡V00训练速度很慢，small模型使用512*512的分辨率比HRNet-W48使用640*640分辨率训练时长还久，显存直接到满。这是模型本身的问题吗，是否适用于多人场景呢？

**Comment by ZiyiZhang27** [comment]
众所周知在GPU上使用深度分离卷积确实是会影响到训练速度的。本论文的主要研究重点在于使模型能够更好地利用长距离的空间上下文信息去学习&理解多人场景中的人体遮挡关系。
