### ISSUE TITLE
请问如何放弃分布式训练

### ISSUE THREAD

**Issue by pydd123** [ZiyiZhang27/HRNeXt#4]
python tools/train.py ${CONFIG_FILE} [optional arguments] 
直接使用该指令会出现
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
需要加上-m torch.distributed.launch
但是我并不想每次都初始化分布式处理的进程组，有取消掉分布式训练的方法吗，这样不方便debug

**Comment by ZiyiZhang27** [comment]
你好！由于我们都是使用多卡训练，未遇到过该问题，无法给予详细的建议。不过你可以尝试到mmpose的repo (https://github.com/open-mmlab/mmpose) 下进行提问，在那里你应该能够得到想要的答复，并且由于本repo使用的mmpose版本较低，建议升级到高版本的mmpose，并将本repo中'/models'和'/config'目录中的模型构建和配置文件迁移过去。另外在此之后也欢迎在本repo创建使用新版本mmpose的branch~
