### ISSUE TITLE
关于文中参数量和结果

### ISSUE THREAD

**Issue by zouxuelian** [ZiyiZhang27/HRNeXt#6]
很高兴能遇见如此优秀的工作，我对您的工作很感兴趣，其中我测试了您提供的crowd pose模型，我发现与文中不相符合，AP0.5=82.5文中的是82.6，且FLOPs=2.4G不是2.5，请问是哪里设置出现问题

**Comment by ZiyiZhang27** [comment]
感谢关注，由于本实验已完成较久，我也不太记得细节了，不过猜测之下应该是当时为了方便统计进行的四舍五入，只是0.1的差距也应该不影响您复现
